version: '2.2'
services:
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    environment:
      - SERVICE_NAME=bouncer-nginx-container
    container_name: bouncer-nginx-container
    image: nginx
    ports:
      - '443:443'
      - '80:80'
    ulimits:
      nproc: 10240
      nofile:
        soft: 10240
        hard: 10240
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf'
      - ./data/certbot/conf:/etc/letsencrypt
      - './config/static:/etc/nginx/static'
      - './certs:/etc/nginx/certs'
      - './config/services-nginx-config:/etc/nginx/conf.d'
      - './logs/bouncer-nginx:/var/log/nginx'
      - './data/certbot/www:/var/www/certbot'
    command: >-
      /bin/bash -c "nginx -g 'daemon off;' & while [ 1 ]; do nginx -s reload &>>
      /tmp/reload.log; sleep 30; clear; done"
    networks:
      - bouncer_bouncer_network
    mem_limit: 100m
    restart: 'on-failure:5'
  bluejay_reporter:
    container_name: bluejay-reporter-container
    image: isagroup/governify-reporter-new:latest
    environment:
      - SERVICE_NAME={{SERVICES_PREFIX}}-reporter-container
      - NODE_ENV=production
      - PORT=80
    networks:
      bouncer_bouncer_network:
        aliases:
          - reporter.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}
    volumes:
      - './logs/bluejay-reporter:/opt/app/logs'
      - './configurations/reporter:/opt/app/src/backend/configurations'
    mem_limit: 400m
    restart: 'unless-stopped'
    depends_on:
      - bluejay_registry_db
      - bluejay_influxdb
  bluejay_grafana:
    container_name: bluejay-grafana-container
    image: isagroup/governify-grafana:1.0.0
    environment:
      - SERVICE_NAME={{SERVICES_PREFIX}}-grafana-container
      - NODE_ENV=production
    networks:
      bouncer_bouncer_network:
        aliases:
          - dashboard.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}
    volumes:
      - 'bluejay_grafana_volume:/var/lib/grafana'
    mem_limit: 400m
    restart: 'unless-stopped'
  bluejay_render:
    container_name: bluejay-render-container
    image: isagroup/governify-render:initialsetup
    environment:
      - SERVICE_NAME={{SERVICES_PREFIX}}-render-container
      - NODE_ENV=production
      - PORT=80
      - LOGIN_USER=governify-admin
      - LOGIN_PASSWORD=governify-project
      - DEFAULT_VIEW=http://assets.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}/api/v1/public/renders/index/view.html
      - DEFAULT_CONTROLLER=http://assets.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}/api/v1/public/renders/index/controller.js
      - DEFAULT_MODEL=http://assets.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}/api/v1/public/renders/index/model.json
    networks:
      bouncer_bouncer_network:
        aliases:
          - ui.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}
    volumes:
      - './logs/render:/opt/app/logs'
    mem_limit: 400m
    restart: 'unless-stopped'
  bluejay_registry_db:
    environment:
      - SERVICE_NAME={{SERVICES_PREFIX}}-registry-db-container
    container_name: bluejay-registry-db-container
    image: mongo
    networks:
      bouncer_bouncer_network:
        aliases:
          - mongo_registry
    volumes:
      - 'bluejay_registry_db_volume:/data/db'
      - './data2import:/data2import'
    mem_limit: 1200m
    restart: 'unless-stopped'
  bluejay_influxdb:
    image: 'influxdb:latest'
    container_name: bluejay-influxdb-container
    volumes:
      - 'bluejay_influxdb_volume:/var/lib/influxdb'
      - './influxdb:/etc/influxdb'
      - './data2import/influxdb:/var/backups'
    networks:
      bouncer_bouncer_network:
        aliases:
          - influxdb
    mem_limit: 1200m
    restart: 'unless-stopped'
  bluejay_registry:
    container_name: bluejay-registry-container
    image: 'isagroup/governify-registry:bluejay'
    networks:
      bouncer_bouncer_network:
        aliases:
          - registry.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}
    environment:
      - NODE_ENV=production
      - PORT=80
      - SERVICE_NAME={{SERVICES_PREFIX}}-registry-container
    volumes:
      - './logs/registry:/opt/app/logs'
      - './static:/opt/app/public/static'
    depends_on:
      - bluejay_registry_db
    mem_limit: 400m
    restart: 'unless-stopped'
  bluejay_eventcollector:
    container_name: bluejay-eventcollector-container
    image: 'isagroup/governify-collector-events:dev'
    environment:
      - SERVICE_NAME={{SERVICES_PREFIX}}-eventcollector-container
      - NODE_ENV=production
      - PORT=80
    networks:
      bouncer_bouncer_network:
        aliases:
          - event.collector.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}
    mem_limit: 400m
    restart: 'unless-stopped'
  bluejay_scopemanager:
    container_name: bluejay-scopemanager-container
    image: 'isagroup/governify-scope-manager:dev'
    environment:
      - SERVICE_NAME={{SERVICES_PREFIX}}-scopemanager-container
      - NODE_ENV=production
      - PORT=80
      - URL_INT_ASSETS_MANAGER_URL=http://assets.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}
      - AUTHORIZED_KEY=
    networks:
      bouncer_bouncer_network:
        aliases:
          - sm.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}
    mem_limit: 400m
    restart: 'unless-stopped'
  bluejay_assetsmanager:
    container_name: bluejay-assetsmanager-container
    image: 'isagroup/governify-assets-manager:latest'
    environment:
      - SERVICE_NAME={{SERVICES_PREFIX}}-assetsmanager-container
      - NODE_ENV=production
      - PORT=80
      - LOGIN_USER=governify-admin
      - LOGIN_PASSWORD=governify-project
      - URL_EXT_ASSETS_MANAGER=https://assets.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}
      - URL_INT_ASSETS_MANAGER_URL=http://assets.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}
      - SERVICES_PREFIX={{SERVICES_PREFIX}}
      - DNS_SUFFIX={{DNS_SUFFIX}}
    networks:
      bouncer_bouncer_network:
        aliases:
          - assets.{{SERVICES_PREFIX}}{{DNS_SUFFIX}}
    volumes:
      - './assets/public:/opt/app/files/public'
      - './assets/private:/opt/app/files/private'
    mem_limit: 400m
    restart: 'unless-stopped'
volumes:
  bluejay_influxdb_volume: null
  bluejay_registry_db_volume: null
  bluejay_grafana_volume: null
networks:
  bouncer_bouncer_network:
    external: true
