name: Node.js CI

on:
  push:
    branches: [ main, develop, master, assets ]
  pull_request:
    branches: [ main, develop, master, assets ]

jobs:
  test:
    name: Install mocha and run tests (docker-compose up, mocha tests and docker-compose down)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies 
      run: npm ci
    - name: Run tests
      run: npm run test
      env:
        CI: true