name: Node.js CI

on:
  push:
    branches: [ main, develop, master, assets ]
  pull_request:
    branches: [ main, develop, master, assets ]

jobs:
  test:
    name: Install mocha and run tests (docker-compose up, mocha tests and docker-compose down)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies 
      run: npm ci
    - name: Add host.docker.internal association to 172.17.0.1
      run: sudo echo "172.17.0.1 host.docker.internal" | sudo tee -a /etc/hosts
    - name: Give permissions to edit assets tests folder
      run: sudo chmod -R 777 tests/configurations/assets
    - name: Run tests
      run: npm run test
      env:
        CI: true